name: Playwright Tests
on:
  push:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: owntracks
          MYSQL_USER: owntracks
          MYSQL_PASSWORD: owntracks
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/actions/setup-gradle@v3
    - run: ./gradlew testdata:run
    - run: ./gradlew backend:bootJar
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: (cd e2e-tests; npx playwright install --with-deps)
    - name: Run Playwright tests
      run: (cd e2e-tests; npx playwright test)
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e-tests/playwright-report/
        retention-days: 30
